### ISSUE TITLE
Refused due to 'X-Frame-Options'

### ISSUE THREAD

**Issue by waheed11** [threemlorg/threeml#1]
Hello,
htmlPlaneGeometry tag works fine with some websites but there are many websites that give an error. Below is an example of the error that I received from w3schools website:
"Refused to display 'https://www.w3schools.com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'."

Please is there any solution or workaround for this issue? 

Thank you.

**Comment by awonnink** [comment]
Hi Waheed11,

I don't think there is a solution for this. It is an Internet security option for sites that don't want their content to be I-framed, as you would certainly want to have for banks, governments etc. that handle sensitive data.

But quite a few sites do not care so much about this, like in the example for Space-x (http://threeml.org/ex/space/). Also, for Youtube the 'share', 'embedded' syntax can be used.

Albert Jan
